import {
  DetailedExceptionLog,
  ExceptionFilterCriteria,
  ExceptionMetrics7Days,
} from '../types/exception';

// Exact 7-Day Metrics Rollup as required
export const EXCEPTION_7DAY_METRICS: ExceptionMetrics7Days = {
  dateRangeLabel: '31 Aug 2026 - 06 Sep 2026 (Last 7 Days)',
  totalExceptions: 148,
  officerOverrides: 38,
  rejectedLots: 42,
  systemWarnings: 45,
  resolved: 125,
  activeOpen: 23,
  resolutionRatePct: 84.5,
  avgResolutionTimeHours: 4.2,
};

// Filter dropdown selections
export const DISTRICT_OPTIONS = [
  'ALL',
  'Bhopal',
  'Indore',
  'Sehore',
  'Dewas',
  'Kendujhar',
  'Harda',
  'Jabalpur',
];

export const MANDI_OPTIONS = [
  'ALL',
  'Karond APMC',
  'Sehore Mandi',
  'Laxmibai Nagar',
  'Kendujhar Central',
  'Dewas Sub-Mandi',
  'Harda Mandi',
  'Jabalpur Krishi Mandi',
];

export const OFFICER_OPTIONS = [
  'ALL',
  'R.K. Sharma (Mandi Sec)',
  'Dilip Sahu (Assayer)',
  'Priya Patel (QC Sup)',
  'Suresh Meena (Supervisor)',
  'AI Sensor Network',
];

export const EXCEPTION_TYPE_OPTIONS = [
  { value: 'ALL', label: 'All Types' },
  { value: 'OFFICER_OVERRIDE', label: 'Officer Overrides', icon: 'shield-checkmark', color: '#1565C0' },
  { value: 'REJECTED_LOT', label: 'Rejected Lots', icon: 'close-circle', color: '#D32F2F' },
  { value: 'SYSTEM_WARNING', label: 'System Warnings', icon: 'warning', color: '#E65100' },
];

export const SEVERITY_OPTIONS = [
  { value: 'ALL', label: 'All Severities' },
  { value: 'CRITICAL', label: 'Critical', color: '#C62828' },
  { value: 'HIGH', label: 'High', color: '#E65100' },
  { value: 'MEDIUM', label: 'Medium', color: '#F57C00' },
  { value: 'LOW', label: 'Low', color: '#2E7D32' },
];

export const STATUS_OPTIONS = [
  { value: 'ALL', label: 'All Statuses' },
  { value: 'OPEN', label: 'Open (Action Needed)', color: '#D32F2F' },
  { value: 'INVESTIGATING', label: 'Investigating', color: '#E65100' },
  { value: 'RESOLVED', label: 'Resolved', color: '#2E7D32' },
];

export const DATE_RANGE_OPTIONS = [
  { value: '7days', label: 'Last 7 Days (Active)' },
  { value: 'today', label: 'Today (06 Sep 2026)' },
  { value: '14days', label: 'Last 14 Days' },
  { value: '30days', label: 'Last 30 Days' },
];

// Initial Filter State
export const DEFAULT_FILTER_CRITERIA: ExceptionFilterCriteria = {
  dateRange: '7days',
  district: 'ALL',
  mandi: 'ALL',
  officer: 'ALL',
  exceptionType: 'ALL',
  severity: 'ALL',
  status: 'ALL',
};

// Rich Sample Exception Logs
export const INITIAL_EXCEPTION_LOGS: DetailedExceptionLog[] = [
  {
    id: 'EXC-2026-0814',
    type: 'OFFICER_OVERRIDE',
    title: 'Moisture Limit Override (15.2% vs 12.0%) Approved',
    description: 'Grain moisture registered at 15.2%, exceeding 12.0% standard FAQ threshold. Discretionary override approved under Departmental Drought Relief Circular #AGRI-2026-MP-04.',
    severity: 'HIGH',
    status: 'OPEN',
    mandiName: 'Sehore Mandi',
    district: 'Sehore',
    farmerName: 'Ramesh Patel',
    farmerId: 'KM-OD-758045',
    farmerMobile: '+91 98261 40812',
    cropName: 'Sharbati Wheat',
    cropHindi: 'गेहूं (Sharbati)',
    lotNumber: 'LT-WH-90812',
    quantityQtl: 42.5,
    authorizedBy: 'R.K. Sharma (Mandi Sec)',
    officerRole: 'Senior Mandi Secretary',
    auditJustification: 'Crop certified for state warehouse silo mechanical drying. Standard moisture deduction ₹25/Qtl applied to payment advice.',
    createdAt: '06 Sep 2026, 10:30 AM',
    daysAgo: 0,
  },
  {
    id: 'EXC-2026-0815',
    type: 'REJECTED_LOT',
    title: 'Paddy Lot Disqualified: Excessive Foreign Matter (5.8%)',
    description: 'Quality assay laboratory test revealed 5.8% foreign inorganic matter and pebbles, severely exceeding the 1.5% maximum allowable FAQ tolerance.',
    severity: 'CRITICAL',
    status: 'OPEN',
    mandiName: 'Karond APMC',
    district: 'Bhopal',
    farmerName: 'Suresh Kumar Verma',
    farmerId: 'KM-MP-89104',
    farmerMobile: '+91 94250 88211',
    cropName: 'Paddy Grade A',
    cropHindi: 'धान (Paddy Grade A)',
    lotNumber: 'LT-PD-89104',
    quantityQtl: 55.0,
    authorizedBy: 'Dilip Sahu (Assayer)',
    officerRole: 'Chief Quality Assayer',
    auditJustification: 'Formal rejection memo #RJ-0815 issued. Farmer advised cleaning/destoning at APMC grading facility before re-entry.',
    createdAt: '06 Sep 2026, 09:15 AM',
    daysAgo: 0,
  },
  {
    id: 'EXC-2026-0816',
    type: 'SYSTEM_WARNING',
    title: 'Weighbridge Scale #2 Calibration Variance Flag (+3.8%)',
    description: 'Gross weight sensor on Scale #2 recorded an anomalous +3.8% tare deviation on 4 consecutive delivery trucks compared to their verified vehicle RFID baseline.',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    mandiName: 'Laxmibai Nagar',
    district: 'Indore',
    authorizedBy: 'AI Sensor Network',
    officerRole: 'IoT Telemetry Sentinel',
    auditJustification: 'Automated lock placed on Scale #2. Inspector alerted to run standard 500kg certified test weights.',
    createdAt: '05 Sep 2026, 04:45 PM',
    daysAgo: 1,
  },
  {
    id: 'EXC-2026-0817',
    type: 'OFFICER_OVERRIDE',
    title: 'Biometric Failure Bypassed via Aadhaar OTP & Voter ID',
    description: 'Farmer biometric scanner failed 3 consecutive thumbprint attempts due to field-worn ridges. Manual biometric bypass approved via Aadhaar OTP verification.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    mandiName: 'Kendujhar Central',
    district: 'Kendujhar',
    farmerName: 'Sunita Devi Mohanta',
    farmerId: 'KM-OD-55912',
    farmerMobile: '+91 93488 56994',
    cropName: 'Swarna Paddy',
    cropHindi: 'धान (Swarna Paddy)',
    lotNumber: 'LT-PD-55912',
    quantityQtl: 60.0,
    authorizedBy: 'Priya Patel (QC Sup)',
    officerRole: 'Assistant Director (Procurement)',
    auditJustification: 'Physical Voter ID card verified and uploaded to portal. Land ownership record cross-verified with Bhulekh portal.',
    createdAt: '05 Sep 2026, 02:20 PM',
    daysAgo: 1,
    resolvedAt: '05 Sep 2026, 03:00 PM',
    resolvedBy: 'Priya Patel (QC Sup)',
  },
  {
    id: 'EXC-2026-0818',
    type: 'REJECTED_LOT',
    title: 'Soybean Lot Rejected: Moisture 19.4% with Fungal Signs',
    description: 'Lot inspection confirmed heavy rain saturation with 19.4% moisture and visible fungal contamination. Failed all safe storage standards.',
    severity: 'CRITICAL',
    status: 'RESOLVED',
    mandiName: 'Laxmibai Nagar',
    district: 'Indore',
    farmerName: 'Kamal Kishore Patidar',
    farmerId: 'KM-MP-38291',
    farmerMobile: '+91 98932 77102',
    cropName: 'Yellow Soybean',
    cropHindi: 'सोयाबीन (Yellow Soybean)',
    lotNumber: 'LT-SB-38291',
    quantityQtl: 38.0,
    authorizedBy: 'Dilip Sahu (Assayer)',
    officerRole: 'Chief Quality Assayer',
    auditJustification: 'Produce rejected to prevent mold contamination of warehouse stack. Farmer accepted rejection slip and diverted to private oil mill.',
    createdAt: '04 Sep 2026, 11:10 AM',
    daysAgo: 2,
    resolvedAt: '04 Sep 2026, 01:30 PM',
    resolvedBy: 'Mandi Secretary',
  },
  {
    id: 'EXC-2026-0819',
    type: 'SYSTEM_WARNING',
    title: 'Queue Gate Congestion Spike (>55 Min Delay)',
    description: 'Vehicle processing queue at Inward Gate #1 surged to 38 loaded vehicles, triggering automated delay flag as wait time exceeded 30-minute SLA.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    mandiName: 'Dewas Sub-Mandi',
    district: 'Dewas',
    authorizedBy: 'AI Sensor Network',
    officerRole: 'Smart Gate Controller',
    auditJustification: 'Auxiliary Gate #3 immediately opened for empty outbound trucks, restoring queue wait time to 18 minutes.',
    createdAt: '04 Sep 2026, 09:30 AM',
    daysAgo: 2,
    resolvedAt: '04 Sep 2026, 10:15 AM',
    resolvedBy: 'Duty Gate Supervisor',
  },
  {
    id: 'EXC-2026-0820',
    type: 'OFFICER_OVERRIDE',
    title: 'Non-Standard Bag Size Accepted for Bulk Weighment',
    description: 'Farmer arrived with 65kg non-standard jute sacks instead of mandatory 50kg bags. Manual tare adjustment override approved.',
    severity: 'LOW',
    status: 'RESOLVED',
    mandiName: 'Dewas Sub-Mandi',
    district: 'Dewas',
    farmerName: 'Gopal Singh Thakur',
    farmerId: 'KM-MP-71209',
    farmerMobile: '+91 97521 34910',
    cropName: 'Lokwan Wheat',
    cropHindi: 'गेहूं (Lokwan)',
    lotNumber: 'LT-WH-71209',
    quantityQtl: 32.0,
    authorizedBy: 'Suresh Meena (Supervisor)',
    officerRole: 'Procurement Supervisor',
    auditJustification: 'Electronic scale configured with customized tare table. Full 32.0 Qtl accounted for without farmer demurrage penalty.',
    createdAt: '03 Sep 2026, 03:15 PM',
    daysAgo: 3,
    resolvedAt: '03 Sep 2026, 03:40 PM',
    resolvedBy: 'Suresh Meena (Supervisor)',
  },
  {
    id: 'EXC-2026-0821',
    type: 'SYSTEM_WARNING',
    title: 'Geo-Fence Route Deviation: Transit Truck MP-09-GE-4412',
    description: 'GPS telemetry alerted a 4.2 km corridor departure for a government grain carrier truck traveling between Mandi yard and Central Silo.',
    severity: 'HIGH',
    status: 'RESOLVED',
    mandiName: 'Harda Mandi',
    district: 'Harda',
    authorizedBy: 'AI Sensor Network',
    officerRole: 'Vehicle Tracking System (VTS)',
    auditJustification: 'Driver contacted by control room. Detour verified due to culvert maintenance on main road. Cargo reached warehouse intact with intact seals.',
    createdAt: '02 Sep 2026, 01:25 PM',
    daysAgo: 4,
    resolvedAt: '02 Sep 2026, 02:10 PM',
    resolvedBy: 'Logistics Desk',
  },
  {
    id: 'EXC-2026-0822',
    type: 'REJECTED_LOT',
    title: 'Black Mustard Produce Contaminated with Argemone Seeds',
    description: 'Field sampling identified 2.1% Argemone mexicana weed seed toxic adulteration. Immediate mandatory disqualification under Food Safety Standards.',
    severity: 'CRITICAL',
    status: 'OPEN',
    mandiName: 'Jabalpur Krishi Mandi',
    district: 'Jabalpur',
    farmerName: 'Dinesh Chandra Joshi',
    farmerId: 'KM-MP-99412',
    farmerMobile: '+91 94065 19283',
    cropName: 'Black Mustard',
    cropHindi: 'सरसों (Black Mustard)',
    lotNumber: 'LT-MS-99412',
    quantityQtl: 19.0,
    authorizedBy: 'Dilip Sahu (Assayer)',
    officerRole: 'Senior Agronomist / Assayer',
    auditJustification: 'Lot quarantine protocol enforced. Rejection notice logged in central portal.',
    createdAt: '01 Sep 2026, 11:45 AM',
    daysAgo: 5,
  },
  {
    id: 'EXC-2026-0823',
    type: 'OFFICER_OVERRIDE',
    title: 'Off-Hours Procurement Clearance for Weather Distress',
    description: 'Severe hailstorm alert issued by IMD for Dewas district. Mandi officer authorized exceptional intake and weighment after 06:00 PM cutoff.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    mandiName: 'Dewas Sub-Mandi',
    district: 'Dewas',
    farmerName: 'Anita Bai Chouhan',
    farmerId: 'KM-MP-44120',
    farmerMobile: '+91 96300 45129',
    cropName: 'Hybrid Maize',
    cropHindi: 'मक्का (Hybrid Maize)',
    lotNumber: 'LT-MZ-44120',
    quantityQtl: 28.5,
    authorizedBy: 'R.K. Sharma (Mandi Sec)',
    officerRole: 'Senior Mandi Secretary',
    auditJustification: 'Distress intake approved under Disaster Preparedness SOP. Produce safely transferred to covered godown before rainfall commenced.',
    createdAt: '31 Aug 2026, 06:40 PM',
    daysAgo: 6,
    resolvedAt: '31 Aug 2026, 07:15 PM',
    resolvedBy: 'R.K. Sharma (Mandi Sec)',
  },
];
