// User roles
export enum UserRole {
  FARMER = 'FARMER',
  OPERATOR = 'OPERATOR',
  ADMIN = 'ADMIN',
}

// Procurement transaction statuses - this is the CORE state machine
export enum TransactionStatus {
  BOOKED = 'BOOKED',
  CHECKED_IN = 'CHECKED_IN',
  WAITING = 'WAITING',
  WEIGHING = 'WEIGHING',
  QUALITY_CHECK = 'QUALITY_CHECK',
  QUALITY_HOLD = 'QUALITY_HOLD',
  PROCUREMENT_PENDING = 'PROCUREMENT_PENDING',
  PROCUREMENT_COMPLETED = 'PROCUREMENT_COMPLETED',
  RECEIPT_GENERATED = 'RECEIPT_GENERATED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CANCELLED = 'CANCELLED',
  MISSED = 'MISSED',
}

// Crop types we support
export enum CropType {
  PADDY = 'PADDY',
  WHEAT = 'WHEAT',
  MAIZE = 'MAIZE',
  SOYBEAN = 'SOYBEAN',
  JOWAR = 'JOWAR',
}

// Quality grades
export enum QualityGrade {
  GRADE_A = 'GRADE_A',
  GRADE_B = 'GRADE_B',
  GRADE_C = 'GRADE_C',
  REJECTED = 'REJECTED',
}

// Exception types
export enum ExceptionType {
  MISSED_TOKEN = 'MISSED_TOKEN',
  CENTRE_DELAY = 'CENTRE_DELAY',
  DOCUMENT_ISSUE = 'DOCUMENT_ISSUE',
  QUALITY_HOLD = 'QUALITY_HOLD',
  QUANTITY_MISMATCH = 'QUANTITY_MISMATCH',
  PROCUREMENT_PENDING = 'PROCUREMENT_PENDING',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_FAILURE = 'PAYMENT_FAILURE',
  CANCELLATION = 'CANCELLATION',
}

// Payment methods (mock)
export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  UPI = 'UPI',
}
